Traceback (most recent call last):
  File "$FILE", line 14, in <module>
    module.compile()
  File "$FILE", line 11, in test
    x(1)
TypeError: Extern `x` is not callable
